# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jim Mitchell
title: Cornell University - Bachelor of Applied Science, Applied Economics and Mangement
email: jim.r.mitchell@protonmail.com
website: www.jmitchellfinance.com
phone: (732) 359-5129

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
#github_username:  jmitchellcornell
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jim-mitchell-803407205
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Professional Summary
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Detail-oriented Personal Banker with a Bachelor of Applied Economics and Management and two years of experieince working with money and customers. Competent and responsive professional capable of acting as a liaison between customers and the bank. Recognized for consistently achieving sales targets and cross-selling bank products.

content:
  - title: Summary of Qualifications
    layout: text
    content: | # this will include new lines to allow paragraph
      - Ability to increase branch revenue through innovative sales strategy
      - Strong foundation of buiilding excellent client rapport to foster satisfaction and loyalty
      - Experience through managing personal, corporate and small business accounts
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Citi Bank
        link: citi.com
        # link_text: boringcompany.com
        sub_title: Private Banker - Student
        caption: December 2018 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cornell University
        caption: 2018 - 2021
        sub_title: Bachelor of Applied Science, Applied Economics and Mangement
        quote: >
          Cornell is a highly rated private university located in Ithaca, New York. It is a large institution with an enrollment of 15,038 undergraduate students. Admissions is extremely competitive as the Cornell acceptance rate is 11%.        
        description: | # this will include new lines to allow paragraphs
          During my time at Cornell I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a hard work and perseverance.

          I spent a lot of my free time as a committee member of the *Social Business and Consulting Club* taking on roles such as *Consultant* and *Executive Director*.
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
